/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description O processo está de pé.
         *
         *     Deliberadamente não toca em modelo, disco nem rede: uma dependência lenta
         *     não pode fazer o orquestrador matar um processo que está perfeitamente vivo.
         */
        get: operations["liveness_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description A aplicação consegue atender: dados carregados e detector calibrado.
         *
         *     Enquanto o limiar não foi calculado, o serviço não recebe tráfego. No v1 o
         *     limiar era calculado na primeira requisição do usuário — que pagava a
         *     varredura de 32 mil registros como latência.
         */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drift": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Drift entre a distribuição de referência e a recente
         * @description PSI por feature, com veredito agregado.
         *
         *     `requires_action` só fica verdadeiro em drift severo (PSI > 0.25). Drift
         *     moderado pede investigação — sazonalidade de vento move distribuição todo
         *     trimestre sem que o modelo tenha piorado.
         */
        get: operations["drift_api_v1_drift_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{report_date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Relatório diário de saúde e previsão
         * @description Analisa um dia de telemetria e devolve saúde, cobertura e previsão.
         *
         *     A data vai no path e é tipada como `date`: o FastAPI valida o formato antes
         *     de a requisição chegar aqui. No v1 a data era uma query string livre
         *     (`?data_string=...`) usada direto como chave de `.loc` num DataFrame — o que
         *     fazia `2022-02-31` e `; DROP` seguirem o mesmo caminho de código.
         *
         *     Todo caminho de erro é tipado: dia inexistente é 404, dia fragmentado
         *     demais é 422, registry fora do ar é 503. Nenhum deles é 500.
         */
        get: operations["daily_report_api_v1_reports__report_date__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cobertura de telemetria dia a dia
         * @description Fração de cada dia com medição, e em quantos trechos contíguos ela vem.
         *
         *     Não roda modelo nenhum — é varredura de índice, e responde em milissegundos
         *     mesmo cobrindo o acervo inteiro.
         *
         *     É a visão que torna a fragmentação da série visível: ver que 2022-01-20 tem
         *     43,8% de cobertura é útil, ver que dezenas de dias têm o mesmo problema é o
         *     que muda a leitura de todos os vereditos do sistema.
         */
        get: operations["coverage_timeline_api_v1_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CoverageSection
         * @description Quanto do dia foi efetivamente analisado.
         */
        CoverageSection: {
            /** Readings */
            readings: number;
            /** Expected Readings */
            expected_readings: number;
            /**
             * Completeness
             * @description Fração do dia com medição
             */
            completeness: number;
            /**
             * Analysed Segments
             * @description Trechos contíguos analisados. >1 indica descontinuidade no dia.
             */
            analysed_segments: number;
            /**
             * Discarded Readings
             * @description Leituras em trechos curtos demais para a janela do modelo
             */
            discarded_readings: number;
            /** Is Fragmented */
            is_fragmented: boolean;
        };
        /**
         * CoverageTimelineResponse
         * @description Cobertura dia a dia num período.
         *
         *     É a visão que torna a fragmentação da série visível ao longo de semanas —
         *     a informação que o v1 não expunha em lugar nenhum.
         */
        CoverageTimelineResponse: {
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /** Mean Completeness */
            mean_completeness: number;
            /** Fragmented Days */
            fragmented_days: number;
            /** Absent Days */
            absent_days: number;
            /** Days */
            days: components["schemas"]["DayCoverageEntry"][];
        };
        /**
         * DailyReportResponse
         * @description Relatório diário completo.
         * @example {
         *       "coverage": {
         *         "analysed_segments": 1,
         *         "completeness": 1,
         *         "discarded_readings": 0,
         *         "expected_readings": 144,
         *         "is_fragmented": false,
         *         "readings": 144
         *       },
         *       "data_range": {
         *         "end": "2022-01-27T23:50:00Z",
         *         "start": "2022-01-14T00:00:00Z"
         *       },
         *       "day": "2022-01-20",
         *       "forecast": {
         *         "model_version": "persistence-baseline@1",
         *         "power_kw": 0,
         *         "power_kw_measured": -0.02,
         *         "target_time": "2022-01-21T00:00:00Z"
         *       },
         *       "health": {
         *         "evaluated_windows": 85,
         *         "exceedances": 0,
         *         "persistence_window": 6,
         *         "previous_period_anomalies": 0,
         *         "previous_period_known": true,
         *         "reason": "Nenhuma janela acima do limiar.",
         *         "status": "OK",
         *         "sustained_anomalies": 0,
         *         "threshold": {
         *           "method": "percentile",
         *           "parameter": 99.5,
         *           "value": 3.21
         *         }
         *       }
         *     }
         */
        DailyReportResponse: {
            /**
             * Day
             * Format: date
             */
            day: string;
            health: components["schemas"]["HealthSection"];
            coverage: components["schemas"]["CoverageSection"];
            forecast?: components["schemas"]["ForecastSection"] | null;
            /**
             * Forecast Unavailable Reason
             * @description Motivo da ausência de previsão. O v1 colocava a string 'Indisponível' dentro do campo numérico, quebrando o tipo.
             */
            forecast_unavailable_reason?: string | null;
            data_range: components["schemas"]["DataRange"];
        };
        /**
         * DataRange
         * @description Janela temporal coberta pelo acervo.
         */
        DataRange: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
        };
        /**
         * DayCoverageEntry
         * @description Cobertura de telemetria de um dia.
         */
        DayCoverageEntry: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Readings */
            readings: number;
            /** Expected Readings */
            expected_readings: number;
            /** Completeness */
            completeness: number;
            /**
             * Segments
             * @description Trechos contíguos. >1 indica descontinuidade no dia.
             */
            segments: number;
            /** Longest Segment */
            longest_segment: number;
            /** Faulted Readings */
            faulted_readings: number;
            /** Is Fragmented */
            is_fragmented: boolean;
            /**
             * Is Absent
             * @description Dia sem nenhuma leitura — distinto de fragmentado, aqui não há o que analisar
             */
            is_absent: boolean;
        };
        /**
         * DriftResponse
         * @description Comparação entre a distribuição de referência e a recente.
         */
        DriftResponse: {
            severity: components["schemas"]["DriftSeverity"];
            /**
             * Requires Action
             * @description True apenas em drift severo; moderado pede investigação, não retreino
             */
            requires_action: boolean;
            /** Worst Feature */
            worst_feature: string;
            /** Features */
            features: components["schemas"]["FeatureDrift"][];
        };
        /**
         * DriftSeverity
         * @description Quanto a distribuição atual se afastou da de referência.
         * @enum {string}
         */
        DriftSeverity: "none" | "moderate" | "severe";
        /** FeatureDrift */
        FeatureDrift: {
            /** Feature */
            feature: string;
            /** Score */
            score: number;
            /** Method */
            method: string;
            severity: components["schemas"]["DriftSeverity"];
        };
        /**
         * ForecastSection
         * @description Previsão de geração para o passo seguinte.
         */
        ForecastSection: {
            /**
             * Power Kw
             * @description Potência prevista **como deve ser exibida**: nunca negativa. A regra é aplicada aqui, no servidor — no v1 vivia no prompt do LLM.
             */
            power_kw: number;
            /**
             * Power Kw Measured
             * @description A saída crua do modelo, que pode ser negativa (consumo parasita). Exposta para que o cliente possa auditar o clamp.
             */
            power_kw_measured: number;
            /**
             * Target Time
             * Format: date-time
             */
            target_time: string;
            /**
             * Model Version
             * @description Identidade do modelo que produziu a previsão
             */
            model_version: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthSection
         * @description Veredito de saúde da turbina.
         */
        HealthSection: {
            status: components["schemas"]["HealthStatus"];
            /**
             * Reason
             * @description Explicação da decisão, em português
             */
            reason: string;
            /**
             * Exceedances
             * @description Janelas acima do limiar, incluindo picos isolados
             */
            exceedances: number;
            /**
             * Sustained Anomalies
             * @description Janelas em corridas longas o bastante para alarmar
             */
            sustained_anomalies: number;
            /** Evaluated Windows */
            evaluated_windows: number;
            /**
             * Persistence Window
             * @description Janelas consecutivas exigidas para caracterizar alerta
             */
            persistence_window: number;
            /**
             * Previous Period Anomalies
             * @description Anomalias na véspera. `null` significa desconhecido — nunca zero.
             */
            previous_period_anomalies?: number | null;
            /** Previous Period Known */
            previous_period_known: boolean;
            threshold: components["schemas"]["ThresholdInfo"];
        };
        /**
         * HealthStatus
         * @description Veredito de saúde da turbina para um período.
         * @enum {string}
         */
        HealthStatus: "OK" | "ALERTA" | "EM_MANUTENCAO";
        /** LivenessResponse */
        LivenessResponse: {
            /**
             * Status
             * @default alive
             */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * ReadinessResponse
         * @description Estado de prontidão para receber tráfego.
         */
        ReadinessResponse: {
            /** Ready */
            ready: boolean;
            /** Checks */
            checks: {
                [key: string]: boolean;
            };
            /** Detail */
            detail?: string | null;
        };
        /**
         * ThresholdInfo
         * @description O limiar usado na decisão — exposto para tornar o alerta auditável.
         */
        ThresholdInfo: {
            /**
             * Value
             * @description Valor do limiar de erro de reconstrução
             */
            value: number;
            /**
             * Method
             * @description Como foi derivado: percentile | std_deviations
             */
            method: string;
            /**
             * Parameter
             * @description O parâmetro do método (ex.: 99.5)
             */
            parameter: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description A aplicação não está pronta para receber tráfego */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    drift_api_v1_drift_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriftResponse"];
                };
            };
            /** @description Histórico insuficiente para comparar dois períodos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    daily_report_api_v1_reports__report_date__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Dia a analisar, em ISO-8601 (YYYY-MM-DD) */
                report_date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyReportResponse"];
                };
            };
            /** @description A data não existe no acervo de telemetria */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A data existe mas não há dado contíguo suficiente para analisar */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Modelo ou fonte de dados indisponível */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    coverage_timeline_api_v1_coverage_get: {
        parameters: {
            query?: {
                /** @description Início do período (padrão: início do acervo) */
                start?: string | null;
                /** @description Fim do período (padrão: fim do acervo) */
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageTimelineResponse"];
                };
            };
            /** @description Período inválido ou maior que o máximo permitido */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
